### ISSUE TITLE
Minor : put page link in the repository description

### ISSUE THREAD

**Issue by thibaultduponchelle** [tpf/grants-perlfoundation-org#11]
It's not that important but could you please put the page link (https://grants.perlfoundation.org/) in he repository description so that we can easily navigate between git repo and perlfoundation grants page.

It just means to replace : 
> Ideas people have suggested which could be proposed as a grant. 

by

> Ideas people have suggested which could be proposed as a grant. https://grants.perlfoundation.org/

It is especially important as google is yet not ranking well this page.

Thank you :smile: 

Sorry for this long story for a 5 seconds modification !

**Comment by lizmat** [comment]
@toddr not sure where to change that, do you?

**Comment by toddr** [comment]
Because of the theme, that would put the link at the head of the grants page. this is why I chose not to do this.

**Comment by thibaultduponchelle** [comment]
Ok I was not aware of this.
