### ISSUE TITLE
User notes for docs.raku.org [raku] [documentation]

### ISSUE THREAD

**Issue by interlab** [tpf/grants-perlfoundation-org#2]
idea:
on the pages of the https://docs.raku.org/... need to add the ability to leave comments with code examples, as on the https://www.php.net/manual/.../...

(sorry my English)

**Comment by lizmat** [comment]
Added with https://github.com/tpf/grants-perlfoundation-org/commit/6f5d85e1fca5765214a2c2e66362fb4ea8d30988
